// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TranNhua.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604090546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpTuong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("chitietsanpham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("dongia")
                        .HasColumnType("numeric");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("soluong")
                        .HasColumnType("numeric");

                    b.Property<string>("thongso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("OpTuong");
                });

            modelBuilder.Entity("TranNhuaDep", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("chitietsanpham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("dongia")
                        .HasColumnType("numeric");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("soluong")
                        .HasColumnType("numeric");

                    b.Property<string>("thongso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("tranxop5")
                        .HasColumnType("numeric");

                    b.Property<decimal>("tranxop8")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("TranNhua");
                });

            modelBuilder.Entity("TranTha", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("chitietsanpham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("dongia")
                        .HasColumnType("numeric");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("soluong")
                        .HasColumnType("numeric");

                    b.Property<string>("thongso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("TranTha");
                });

            modelBuilder.Entity("VachNgan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("chitietsanpham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("noidung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("soluong")
                        .HasColumnType("numeric");

                    b.Property<string>("thongso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("vach1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("vach2")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("VachNgan");
                });
#pragma warning restore 612, 618
        }
    }
}
